#
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db-game:5432/game
    username: postgres
    password: postgres
  security:
    user:
      name: app-game
      password: app-game
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
#
management:
  server:
    port: 7200
