#
spring:
  datasource:
    url: jdbc:h2:file:~/spring-cloud/game
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  security:
    user:
      name: app-game
      password: app-game
#
management:
  server:
    port: 7200
