apiVersion: v1
kind: Pod
metadata:
  name: envauthorizationpod
  labels:
    name: envauthorization
spec:
  containers:
    - name: env-authorization-container
      image: env-authorization:0.0.1
      env:
        - name: spring.profiles.active
          value: kubernetes
