apiVersion: v1
kind: Service
metadata:
  name: envauthorizationservice
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: envauthorization
  ports:
    - nodePort: 30800
      port: 8000
