apiVersion: apps/v1
kind: Deployment
metadata:
  name: envauthorization
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: envauthorization
  template:
    metadata:
      name: envauthorization
      labels:
        app.kubernetes.io/name: envauthorization
    spec:
      containers:
        - name: envauthorization-container
          image: env-authorization:0.0.1
          env:
            - name: spring.profiles.active
              value: kubernetes,jwt
