apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-sba
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: env-sba
  template:
    metadata:
      name: env-sba
      labels:
        app.kubernetes.io/name: env-sba
    spec:
      containers:
        - name: env-sba
          image: env-sba:0.0.1
          env:
            - name: spring.profiles.active
              value: kubernetes,jwt
            - name: spring.cloud.kubernetes.enabled
              value: "true"
            - name: spring.cloud.kubernetes.config.enabled
              value: "true"
            - name: spring.cloud.kubernetes.secrets.enabled
              value: "true"
            - name: spring.cloud.kubernetes.discovery.enabled
              value: "true"
