apiVersion: v1
kind: ConfigMap
metadata:
  name: env-sba
data:
  application.properties: |-
    spring.jmx.enabled=true
    spring.security.user.name=env-sba
    spring.security.user.password=env-sba
