apiVersion: v1
kind: Service
metadata:
  name: env-authorization
  labels:
    #
    sba-client: "true"
    # pass metadata to sba
    user.name: env-authorization
    user.password: env-authorization
    management.port: "7000"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: env-authorization
  ports:
    - nodePort: 30800
      port: 8000
