apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: env-authorization
  name: env-authorization
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: env-authorization
  template:
    metadata:
      name: env-authorization
      labels:
        app.kubernetes.io/name: env-authorization
    spec:
      containers:
        - name: env-authorization-container
          image: env-authorization:0.0.1
          env:
            - name: spring.profiles.active
              value: kubernetes,jwt
            - name: spring.cloud.kubernetes.enabled
              value: "true"
            - name: spring.cloud.kubernetes.discovery.enabled
              value: "true"
            - name: spring.cloud.kubernetes.config.enabled
              value: "true"
            - name: spring.cloud.kubernetes.secrets.enabled
              value: "true"
          volumeMounts:
            - name: volume-secret-env-authorization
              mountPath: /etc/secret
      volumes:
        - name: volume-secret-env-authorization
          secret:
            secretName: env-authorization
