apiVersion: v1
kind: Secret
metadata:
  namespace: env-authorization
  name: env-authorization
type: Opaque
data:
  spring.security.user.name: ZW52LWF1dGhvcml6YXRpb24=
  spring.security.user.password: ZW52LWF1dGhvcml6YXRpb24=
