#
version: @project.version@
#
server:
  error:
    include-binding-errors: always
#
spring:
  profiles:
    active: default
  datasource:
    url: jdbc:h2:mem:reference
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
