apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-authorization
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: env-authorization
  template:
    metadata:
      name: env-authorization
      labels:
        app.kubernetes.io/name: env-authorization
    spec:
      containers:
        - name: env-authorization-container
          image: env-authorization:0.0.1
          env:
            - name: spring.profiles.active
              value: kubernetes,jwt
            - name: spring.cloud.kubernetes.enabled
              value: "true"
            - name: spring.cloud.kubernetes.config.enabled
              value: "true"
            - name: spring.cloud.kubernetes.secrets.enabled
              value: "true"
            - name: spring.cloud.kubernetes.discovery.enabled
              value: "true"
            - name: spring.zipkin.enabled
              value: "true"
            - name: spring.sleuth.enabled
              value: "true"
            - name: spring.zipkin.sender.type
              value: kafka
            - name: spring.kafka.bootstrap-servers
              value: env-kafka:9091
#            - name: logging.config
#              value: /var/logback/logback.xml
          volumeMounts:
            - name: env-authorization-secret
              mountPath: /etc/secret
            - name: logback
              mountPath: /var/logback/logback.xml
              subPath: logback.xml
      volumes:
        - name: env-authorization-secret
          secret:
            secretName: env-authorization
        - name: logback
          configMap:
            name: env-authorization
            items:
              - key: logback.xml
                path: logback.xml
