apiVersion: v1
kind: ConfigMap
metadata:
  name: env-authorization
data:
  application.properties: |-
    spring.jmx.enabled=true
#    spring.sleuth.enabled=true
#    spring.sleuth.sampler.probability=1.0
#    spring.zipkin.enabled=true
#    spring.zipkin.base-url=http://zipkin:9411/
