---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: env-kibana
  template:
    metadata:
      name: env-kibana
      labels:
        app.kubernetes.io/name: env-kibana
    spec:
      containers:
        - name: env-kibana
          image: kibana:7.2.0
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://env-elasticsearch:9200
---
apiVersion: v1
kind: Service
metadata:
  name: env-kibana
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: env-kibana
  ports:
    - port: 5601
      nodePort: 30560
