#
version: @project.version@
#
spring:
  application:
    name: env-authorization
  profiles:
    active: default
  datasource:
    url: jdbc:h2:mem:auth
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
